#pragma once

#define VK_NO_PROTOTYPES
#define VK_ENABLE_BETA_EXTENSIONS
#include "../../third-party/vulkan/vulkan.h"
#undef far
#undef near
#undef max
#undef min
#undef None
#undef Success

#ifdef __VK_API_DEF__
#define EXTERN_FUNC
#else
#define EXTERN_FUNC extern
#endif

#define vkCreateInstance ray_vkCreateInstance
#define vkDestroyInstance ray_vkDestroyInstance
#define vkEnumerateInstanceLayerProperties ray_vkEnumerateInstanceLayerProperties
#define vkEnumerateInstanceExtensionProperties ray_vkEnumerateInstanceExtensionProperties
#define vkGetInstanceProcAddr ray_vkGetInstanceProcAddr

#define vkEnumeratePhysicalDevices ray_vkEnumeratePhysicalDevices
#define vkGetPhysicalDeviceProperties ray_vkGetPhysicalDeviceProperties
#define vkGetPhysicalDeviceProperties2KHR ray_vkGetPhysicalDeviceProperties2KHR
#define vkGetPhysicalDeviceFeatures ray_vkGetPhysicalDeviceFeatures
#define vkGetPhysicalDeviceQueueFamilyProperties ray_vkGetPhysicalDeviceQueueFamilyProperties

#define vkCreateDevice ray_vkCreateDevice
#define vkDestroyDevice ray_vkDestroyDevice

#define vkEnumerateDeviceExtensionProperties ray_vkEnumerateDeviceExtensionProperties

#define vkCreateDebugReportCallbackEXT ray_vkCreateDebugReportCallbackEXT
#define vkDestroyDebugReportCallbackEXT ray_vkDestroyDebugReportCallbackEXT
#define vkDebugReportMessageEXT ray_vkDebugReportMessageEXT

#if defined(VK_USE_PLATFORM_WIN32_KHR)
#define vkCreateWin32SurfaceKHR ray_vkCreateWin32SurfaceKHR
#elif defined(VK_USE_PLATFORM_XLIB_KHR)
#define vkCreateXlibSurfaceKHR ray_vkCreateXlibSurfaceKHR
#elif defined(VK_USE_PLATFORM_IOS_MVK)
#define vkCreateIOSSurfaceMVK ray_vkCreateIOSSurfaceMVK
#endif
#define vkDestroySurfaceKHR ray_vkDestroySurfaceKHR
#define vkGetPhysicalDeviceSurfaceSupportKHR ray_vkGetPhysicalDeviceSurfaceSupportKHR
#define vkGetPhysicalDeviceSurfaceCapabilitiesKHR ray_vkGetPhysicalDeviceSurfaceCapabilitiesKHR
#define vkGetPhysicalDeviceSurfaceFormatsKHR ray_vkGetPhysicalDeviceSurfaceFormatsKHR

#define vkGetPhysicalDeviceSurfacePresentModesKHR ray_vkGetPhysicalDeviceSurfacePresentModesKHR
#define vkCreateSwapchainKHR ray_vkCreateSwapchainKHR
#define vkDestroySwapchainKHR ray_vkDestroySwapchainKHR
#define vkGetDeviceQueue ray_vkGetDeviceQueue
#define vkCreateCommandPool ray_vkCreateCommandPool
#define vkDestroyCommandPool ray_vkDestroyCommandPool
#define vkAllocateCommandBuffers ray_vkAllocateCommandBuffers
#define vkFreeCommandBuffers ray_vkFreeCommandBuffers
#define vkDeviceWaitIdle ray_vkDeviceWaitIdle

#define vkGetSwapchainImagesKHR ray_vkGetSwapchainImagesKHR

#define vkCreateFence ray_vkCreateFence
#define vkWaitForFences ray_vkWaitForFences
#define vkResetFences ray_vkResetFences
#define vkDestroyFence ray_vkDestroyFence
#define vkGetFenceStatus ray_vkGetFenceStatus

#define vkBeginCommandBuffer ray_vkBeginCommandBuffer
#define vkEndCommandBuffer ray_vkEndCommandBuffer
#define vkCmdPipelineBarrier ray_vkCmdPipelineBarrier

#define vkQueueSubmit ray_vkQueueSubmit
#define vkQueueWaitIdle ray_vkQueueWaitIdle
#define vkResetCommandBuffer ray_vkResetCommandBuffer
#define vkCreateImageView ray_vkCreateImageView
#define vkDestroyImageView ray_vkDestroyImageView

#define vkAcquireNextImageKHR ray_vkAcquireNextImageKHR
#define vkQueuePresentKHR ray_vkQueuePresentKHR

#define vkGetPhysicalDeviceMemoryProperties ray_vkGetPhysicalDeviceMemoryProperties
#define vkGetPhysicalDeviceFormatProperties ray_vkGetPhysicalDeviceFormatProperties
#define vkGetPhysicalDeviceImageFormatProperties ray_vkGetPhysicalDeviceImageFormatProperties

#define vkCreateImage ray_vkCreateImage
#define vkDestroyImage ray_vkDestroyImage

#define vkGetImageMemoryRequirements ray_vkGetImageMemoryRequirements
#define vkAllocateMemory ray_vkAllocateMemory
#define vkFreeMemory ray_vkFreeMemory
#define vkBindImageMemory ray_vkBindImageMemory

#define vkCreateRenderPass ray_vkCreateRenderPass
#define vkDestroyRenderPass ray_vkDestroyRenderPass

#define vkCreateFramebuffer ray_vkCreateFramebuffer
#define vkDestroyFramebuffer ray_vkDestroyFramebuffer

#define vkCreateBuffer ray_vkCreateBuffer
#define vkGetBufferDeviceAddressKHR ray_vkGetBufferDeviceAddressKHR
#define vkBindBufferMemory ray_vkBindBufferMemory
#define vkDestroyBuffer ray_vkDestroyBuffer

#define vkCreateBufferView ray_vkCreateBufferView
#define vkDestroyBufferView ray_vkDestroyBufferView

#define vkMapMemory ray_vkMapMemory
#define vkUnmapMemory ray_vkUnmapMemory
#define vkFlushMappedMemoryRanges ray_vkFlushMappedMemoryRanges
#define vkInvalidateMappedMemoryRanges ray_vkInvalidateMappedMemoryRanges

#define vkCreateShaderModule ray_vkCreateShaderModule
#define vkDestroyShaderModule ray_vkDestroyShaderModule

#define vkCreateDescriptorSetLayout ray_vkCreateDescriptorSetLayout
#define vkDestroyDescriptorSetLayout ray_vkDestroyDescriptorSetLayout

#define vkCreatePipelineLayout ray_vkCreatePipelineLayout
#define vkDestroyPipelineLayout ray_vkDestroyPipelineLayout

#define vkCreateGraphicsPipelines ray_vkCreateGraphicsPipelines
#define vkCreateComputePipelines ray_vkCreateComputePipelines
#define vkDestroyPipeline ray_vkDestroyPipeline

#define vkCreateSemaphore ray_vkCreateSemaphore
#define vkDestroySemaphore ray_vkDestroySemaphore

#define vkCreateSampler ray_vkCreateSampler
#define vkDestroySampler ray_vkDestroySampler

#define vkCreateDescriptorPool ray_vkCreateDescriptorPool
#define vkDestroyDescriptorPool ray_vkDestroyDescriptorPool
#define vkResetDescriptorPool ray_vkResetDescriptorPool

#define vkAllocateDescriptorSets ray_vkAllocateDescriptorSets
#define vkFreeDescriptorSets ray_vkFreeDescriptorSets
#define vkUpdateDescriptorSets ray_vkUpdateDescriptorSets

#define vkCreateQueryPool ray_vkCreateQueryPool
#define vkDestroyQueryPool ray_vkDestroyQueryPool
#define vkGetQueryPoolResults ray_vkGetQueryPoolResults

#define vkCreateAccelerationStructureKHR ray_vkCreateAccelerationStructureKHR
#define vkDestroyAccelerationStructureKHR ray_vkDestroyAccelerationStructureKHR

#define vkCmdBeginRenderPass ray_vkCmdBeginRenderPass
#define vkCmdBindPipeline ray_vkCmdBindPipeline
#define vkCmdSetViewport ray_vkCmdSetViewport
#define vkCmdSetScissor ray_vkCmdSetScissor
#define vkCmdBindDescriptorSets ray_vkCmdBindDescriptorSets
#define vkCmdBindVertexBuffers ray_vkCmdBindVertexBuffers
#define vkCmdBindIndexBuffer ray_vkCmdBindIndexBuffer
#define vkCmdDraw ray_vkCmdDraw
#define vkCmdDrawIndexed ray_vkCmdDrawIndexed
#define vkCmdEndRenderPass ray_vkCmdEndRenderPass
#define vkCmdCopyBufferToImage ray_vkCmdCopyBufferToImage
#define vkCmdCopyImageToBuffer ray_vkCmdCopyImageToBuffer
#define vkCmdCopyBuffer ray_vkCmdCopyBuffer
#define vkCmdFillBuffer ray_vkCmdFillBuffer
#define vkCmdUpdateBuffer ray_vkCmdUpdateBuffer
#define vkCmdPushConstants ray_vkCmdPushConstants
#define vkCmdBlitImage ray_vkCmdBlitImage
#define vkCmdClearColorImage ray_vkCmdClearColorImage
#define vkCmdClearAttachments ray_vkCmdClearAttachments
#define vkCmdCopyImage ray_vkCmdCopyImage
#define vkCmdDispatch ray_vkCmdDispatch
#define vkCmdDispatchIndirect ray_vkCmdDispatchIndirect
#define vkCmdResetQueryPool ray_vkCmdResetQueryPool

#define vkCmdBeginRenderingKHR ray_vkCmdBeginRenderingKHR
#define vkCmdEndRenderingKHR ray_vkCmdEndRenderingKHR

#define vkCmdBuildAccelerationStructuresKHR ray_vkCmdBuildAccelerationStructuresKHR
#define vkCmdWriteAccelerationStructuresPropertiesKHR ray_vkCmdWriteAccelerationStructuresPropertiesKHR
#define vkCmdCopyAccelerationStructureKHR ray_vkCmdCopyAccelerationStructureKHR
#define vkCmdTraceRaysKHR ray_vkCmdTraceRaysKHR
#define vkCmdTraceRaysIndirectKHR ray_vkCmdTraceRaysIndirectKHR

#define vkCmdBeginDebugUtilsLabelEXT ray_vkCmdBeginDebugUtilsLabelEXT
#define vkCmdEndDebugUtilsLabelEXT ray_vkCmdEndDebugUtilsLabelEXT
#define vkSetDebugUtilsObjectNameEXT ray_vkSetDebugUtilsObjectNameEXT

#define vkCmdSetDepthBias ray_vkCmdSetDepthBias

#define vkGetBufferMemoryRequirements ray_vkGetBufferMemoryRequirements
#define vkGetAccelerationStructureBuildSizesKHR ray_vkGetAccelerationStructureBuildSizesKHR
#define vkGetAccelerationStructureDeviceAddressKHR ray_vkGetAccelerationStructureDeviceAddressKHR
#define vkGetRayTracingShaderGroupHandlesKHR ray_vkGetRayTracingShaderGroupHandlesKHR

#define vkCreateRayTracingPipelinesKHR ray_vkCreateRayTracingPipelinesKHR

#define vkCreateQueryPool ray_vkCreateQueryPool
#define vkCmdWriteTimestamp ray_vkCmdWriteTimestamp

extern "C" {
EXTERN_FUNC PFN_vkCreateInstance ray_vkCreateInstance;
EXTERN_FUNC PFN_vkDestroyInstance ray_vkDestroyInstance;
EXTERN_FUNC PFN_vkEnumerateInstanceLayerProperties ray_vkEnumerateInstanceLayerProperties;
EXTERN_FUNC PFN_vkEnumerateInstanceExtensionProperties ray_vkEnumerateInstanceExtensionProperties;
EXTERN_FUNC PFN_vkGetInstanceProcAddr ray_vkGetInstanceProcAddr;

EXTERN_FUNC PFN_vkEnumeratePhysicalDevices ray_vkEnumeratePhysicalDevices;
EXTERN_FUNC PFN_vkGetPhysicalDeviceProperties ray_vkGetPhysicalDeviceProperties;
EXTERN_FUNC PFN_vkGetPhysicalDeviceProperties2KHR ray_vkGetPhysicalDeviceProperties2KHR;
EXTERN_FUNC PFN_vkGetPhysicalDeviceFeatures ray_vkGetPhysicalDeviceFeatures;
EXTERN_FUNC PFN_vkGetPhysicalDeviceQueueFamilyProperties ray_vkGetPhysicalDeviceQueueFamilyProperties;

EXTERN_FUNC PFN_vkCreateDevice ray_vkCreateDevice;
EXTERN_FUNC PFN_vkDestroyDevice ray_vkDestroyDevice;

EXTERN_FUNC PFN_vkEnumerateDeviceExtensionProperties ray_vkEnumerateDeviceExtensionProperties;

EXTERN_FUNC PFN_vkCreateDebugReportCallbackEXT ray_vkCreateDebugReportCallbackEXT;
EXTERN_FUNC PFN_vkDestroyDebugReportCallbackEXT ray_vkDestroyDebugReportCallbackEXT;
EXTERN_FUNC PFN_vkDebugReportMessageEXT ray_vkDebugReportMessageEXT;

#if defined(VK_USE_PLATFORM_WIN32_KHR)
EXTERN_FUNC PFN_vkCreateWin32SurfaceKHR ray_vkCreateWin32SurfaceKHR;
#elif defined(VK_USE_PLATFORM_XLIB_KHR)
EXTERN_FUNC PFN_vkCreateXlibSurfaceKHR ray_vkCreateXlibSurfaceKHR;
#elif defined(VK_USE_PLATFORM_IOS_MVK)
EXTERN_FUNC PFN_vkCreateIOSSurfaceMVK ray_vkCreateIOSSurfaceMVK;
#elif defined(VK_USE_PLATFORM_MACOS_MVK)
EXTERN_FUNC PFN_vkCreateMacOSSurfaceMVK vkCreateMacOSSurfaceMVK;
#endif
EXTERN_FUNC PFN_vkDestroySurfaceKHR ray_vkDestroySurfaceKHR;
EXTERN_FUNC PFN_vkGetPhysicalDeviceSurfaceSupportKHR ray_vkGetPhysicalDeviceSurfaceSupportKHR;
EXTERN_FUNC PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR ray_vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
EXTERN_FUNC PFN_vkGetPhysicalDeviceSurfaceFormatsKHR ray_vkGetPhysicalDeviceSurfaceFormatsKHR;

EXTERN_FUNC PFN_vkGetPhysicalDeviceSurfacePresentModesKHR ray_vkGetPhysicalDeviceSurfacePresentModesKHR;
EXTERN_FUNC PFN_vkCreateSwapchainKHR ray_vkCreateSwapchainKHR;
EXTERN_FUNC PFN_vkDestroySwapchainKHR ray_vkDestroySwapchainKHR;
EXTERN_FUNC PFN_vkGetDeviceQueue ray_vkGetDeviceQueue;
EXTERN_FUNC PFN_vkCreateCommandPool ray_vkCreateCommandPool;
EXTERN_FUNC PFN_vkDestroyCommandPool ray_vkDestroyCommandPool;
EXTERN_FUNC PFN_vkAllocateCommandBuffers ray_vkAllocateCommandBuffers;
EXTERN_FUNC PFN_vkFreeCommandBuffers ray_vkFreeCommandBuffers;
EXTERN_FUNC PFN_vkDeviceWaitIdle ray_vkDeviceWaitIdle;

EXTERN_FUNC PFN_vkGetSwapchainImagesKHR ray_vkGetSwapchainImagesKHR;

EXTERN_FUNC PFN_vkCreateFence ray_vkCreateFence;
EXTERN_FUNC PFN_vkWaitForFences ray_vkWaitForFences;
EXTERN_FUNC PFN_vkResetFences ray_vkResetFences;
EXTERN_FUNC PFN_vkDestroyFence ray_vkDestroyFence;
EXTERN_FUNC PFN_vkGetFenceStatus ray_vkGetFenceStatus;

EXTERN_FUNC PFN_vkBeginCommandBuffer ray_vkBeginCommandBuffer;
EXTERN_FUNC PFN_vkEndCommandBuffer ray_vkEndCommandBuffer;
EXTERN_FUNC PFN_vkCmdPipelineBarrier ray_vkCmdPipelineBarrier;

EXTERN_FUNC PFN_vkQueueSubmit ray_vkQueueSubmit;
EXTERN_FUNC PFN_vkQueueWaitIdle ray_vkQueueWaitIdle;
EXTERN_FUNC PFN_vkResetCommandBuffer ray_vkResetCommandBuffer;
EXTERN_FUNC PFN_vkCreateImageView ray_vkCreateImageView;
EXTERN_FUNC PFN_vkDestroyImageView ray_vkDestroyImageView;

EXTERN_FUNC PFN_vkAcquireNextImageKHR ray_vkAcquireNextImageKHR;
EXTERN_FUNC PFN_vkQueuePresentKHR ray_vkQueuePresentKHR;

EXTERN_FUNC PFN_vkGetPhysicalDeviceMemoryProperties ray_vkGetPhysicalDeviceMemoryProperties;
EXTERN_FUNC PFN_vkGetPhysicalDeviceFormatProperties ray_vkGetPhysicalDeviceFormatProperties;
EXTERN_FUNC PFN_vkGetPhysicalDeviceImageFormatProperties ray_vkGetPhysicalDeviceImageFormatProperties;

EXTERN_FUNC PFN_vkCreateImage ray_vkCreateImage;
EXTERN_FUNC PFN_vkDestroyImage ray_vkDestroyImage;

EXTERN_FUNC PFN_vkGetImageMemoryRequirements ray_vkGetImageMemoryRequirements;
EXTERN_FUNC PFN_vkAllocateMemory ray_vkAllocateMemory;
EXTERN_FUNC PFN_vkFreeMemory ray_vkFreeMemory;
EXTERN_FUNC PFN_vkBindImageMemory ray_vkBindImageMemory;

EXTERN_FUNC PFN_vkCreateRenderPass ray_vkCreateRenderPass;
EXTERN_FUNC PFN_vkDestroyRenderPass ray_vkDestroyRenderPass;

EXTERN_FUNC PFN_vkCreateFramebuffer ray_vkCreateFramebuffer;
EXTERN_FUNC PFN_vkDestroyFramebuffer ray_vkDestroyFramebuffer;

EXTERN_FUNC PFN_vkCreateBuffer ray_vkCreateBuffer;
EXTERN_FUNC PFN_vkGetBufferDeviceAddressKHR ray_vkGetBufferDeviceAddressKHR;
EXTERN_FUNC PFN_vkBindBufferMemory ray_vkBindBufferMemory;
EXTERN_FUNC PFN_vkDestroyBuffer ray_vkDestroyBuffer;

EXTERN_FUNC PFN_vkCreateBufferView ray_vkCreateBufferView;
EXTERN_FUNC PFN_vkDestroyBufferView ray_vkDestroyBufferView;

EXTERN_FUNC PFN_vkMapMemory ray_vkMapMemory;
EXTERN_FUNC PFN_vkUnmapMemory ray_vkUnmapMemory;
EXTERN_FUNC PFN_vkFlushMappedMemoryRanges ray_vkFlushMappedMemoryRanges;
EXTERN_FUNC PFN_vkInvalidateMappedMemoryRanges ray_vkInvalidateMappedMemoryRanges;

EXTERN_FUNC PFN_vkCreateShaderModule ray_vkCreateShaderModule;
EXTERN_FUNC PFN_vkDestroyShaderModule ray_vkDestroyShaderModule;

EXTERN_FUNC PFN_vkCreateDescriptorSetLayout ray_vkCreateDescriptorSetLayout;
EXTERN_FUNC PFN_vkDestroyDescriptorSetLayout ray_vkDestroyDescriptorSetLayout;

EXTERN_FUNC PFN_vkCreatePipelineLayout ray_vkCreatePipelineLayout;
EXTERN_FUNC PFN_vkDestroyPipelineLayout ray_vkDestroyPipelineLayout;

EXTERN_FUNC PFN_vkCreateGraphicsPipelines ray_vkCreateGraphicsPipelines;
EXTERN_FUNC PFN_vkCreateComputePipelines ray_vkCreateComputePipelines;
EXTERN_FUNC PFN_vkDestroyPipeline ray_vkDestroyPipeline;

EXTERN_FUNC PFN_vkCreateSemaphore ray_vkCreateSemaphore;
EXTERN_FUNC PFN_vkDestroySemaphore ray_vkDestroySemaphore;

EXTERN_FUNC PFN_vkCreateSampler ray_vkCreateSampler;
EXTERN_FUNC PFN_vkDestroySampler ray_vkDestroySampler;

EXTERN_FUNC PFN_vkCreateDescriptorPool ray_vkCreateDescriptorPool;
EXTERN_FUNC PFN_vkDestroyDescriptorPool ray_vkDestroyDescriptorPool;
EXTERN_FUNC PFN_vkResetDescriptorPool ray_vkResetDescriptorPool;

EXTERN_FUNC PFN_vkAllocateDescriptorSets ray_vkAllocateDescriptorSets;
EXTERN_FUNC PFN_vkFreeDescriptorSets ray_vkFreeDescriptorSets;
EXTERN_FUNC PFN_vkUpdateDescriptorSets ray_vkUpdateDescriptorSets;

EXTERN_FUNC PFN_vkCreateQueryPool ray_vkCreateQueryPool;
EXTERN_FUNC PFN_vkDestroyQueryPool ray_vkDestroyQueryPool;
EXTERN_FUNC PFN_vkGetQueryPoolResults ray_vkGetQueryPoolResults;

EXTERN_FUNC PFN_vkCreateAccelerationStructureKHR ray_vkCreateAccelerationStructureKHR;
EXTERN_FUNC PFN_vkDestroyAccelerationStructureKHR ray_vkDestroyAccelerationStructureKHR;

EXTERN_FUNC PFN_vkCmdBeginRenderPass ray_vkCmdBeginRenderPass;
EXTERN_FUNC PFN_vkCmdBindPipeline ray_vkCmdBindPipeline;
EXTERN_FUNC PFN_vkCmdSetViewport ray_vkCmdSetViewport;
EXTERN_FUNC PFN_vkCmdSetScissor ray_vkCmdSetScissor;
EXTERN_FUNC PFN_vkCmdBindDescriptorSets ray_vkCmdBindDescriptorSets;
EXTERN_FUNC PFN_vkCmdBindVertexBuffers ray_vkCmdBindVertexBuffers;
EXTERN_FUNC PFN_vkCmdBindIndexBuffer ray_vkCmdBindIndexBuffer;
EXTERN_FUNC PFN_vkCmdDraw ray_vkCmdDraw;
EXTERN_FUNC PFN_vkCmdDrawIndexed ray_vkCmdDrawIndexed;
EXTERN_FUNC PFN_vkCmdEndRenderPass ray_vkCmdEndRenderPass;
EXTERN_FUNC PFN_vkCmdCopyBufferToImage ray_vkCmdCopyBufferToImage;
EXTERN_FUNC PFN_vkCmdCopyImageToBuffer ray_vkCmdCopyImageToBuffer;
EXTERN_FUNC PFN_vkCmdCopyBuffer ray_vkCmdCopyBuffer;
EXTERN_FUNC PFN_vkCmdFillBuffer ray_vkCmdFillBuffer;
EXTERN_FUNC PFN_vkCmdUpdateBuffer ray_vkCmdUpdateBuffer;
EXTERN_FUNC PFN_vkCmdPushConstants ray_vkCmdPushConstants;
EXTERN_FUNC PFN_vkCmdBlitImage ray_vkCmdBlitImage;
EXTERN_FUNC PFN_vkCmdClearColorImage ray_vkCmdClearColorImage;
EXTERN_FUNC PFN_vkCmdClearAttachments ray_vkCmdClearAttachments;
EXTERN_FUNC PFN_vkCmdCopyImage ray_vkCmdCopyImage;
EXTERN_FUNC PFN_vkCmdDispatch ray_vkCmdDispatch;
EXTERN_FUNC PFN_vkCmdDispatchIndirect ray_vkCmdDispatchIndirect;
EXTERN_FUNC PFN_vkCmdResetQueryPool ray_vkCmdResetQueryPool;
EXTERN_FUNC PFN_vkCmdWriteTimestamp ray_vkCmdWriteTimestamp;

EXTERN_FUNC PFN_vkCmdBeginRenderingKHR ray_vkCmdBeginRenderingKHR;
EXTERN_FUNC PFN_vkCmdEndRenderingKHR ray_vkCmdEndRenderingKHR;

EXTERN_FUNC PFN_vkCmdBuildAccelerationStructuresKHR ray_vkCmdBuildAccelerationStructuresKHR;
EXTERN_FUNC PFN_vkCmdWriteAccelerationStructuresPropertiesKHR ray_vkCmdWriteAccelerationStructuresPropertiesKHR;
EXTERN_FUNC PFN_vkCmdCopyAccelerationStructureKHR ray_vkCmdCopyAccelerationStructureKHR;
EXTERN_FUNC PFN_vkCmdTraceRaysKHR ray_vkCmdTraceRaysKHR;
EXTERN_FUNC PFN_vkCmdTraceRaysIndirectKHR ray_vkCmdTraceRaysIndirectKHR;

EXTERN_FUNC PFN_vkCmdBeginDebugUtilsLabelEXT ray_vkCmdBeginDebugUtilsLabelEXT;
EXTERN_FUNC PFN_vkCmdEndDebugUtilsLabelEXT ray_vkCmdEndDebugUtilsLabelEXT;
EXTERN_FUNC PFN_vkSetDebugUtilsObjectNameEXT ray_vkSetDebugUtilsObjectNameEXT;

EXTERN_FUNC PFN_vkCmdSetDepthBias ray_vkCmdSetDepthBias;

EXTERN_FUNC PFN_vkGetBufferMemoryRequirements ray_vkGetBufferMemoryRequirements;
EXTERN_FUNC PFN_vkGetAccelerationStructureBuildSizesKHR ray_vkGetAccelerationStructureBuildSizesKHR;
EXTERN_FUNC PFN_vkGetAccelerationStructureDeviceAddressKHR ray_vkGetAccelerationStructureDeviceAddressKHR;
EXTERN_FUNC PFN_vkGetRayTracingShaderGroupHandlesKHR ray_vkGetRayTracingShaderGroupHandlesKHR;

EXTERN_FUNC PFN_vkCreateRayTracingPipelinesKHR ray_vkCreateRayTracingPipelinesKHR;
}

#define VK_API_VERSION_MAJOR(version) (((uint32_t)(version) >> 22) & 0x7FU)
#define VK_API_VERSION_MINOR(version) (((uint32_t)(version) >> 12) & 0x3FFU)

namespace Ray {
class ILog;
namespace Vk {
bool LoadVulkan(ILog *log);
bool LoadVulkanExtensions(VkInstance instance, ILog *log);
} // namespace Vk
} // namespace Ray
