#ifndef PREPARE_INDIR_ARGS_INTERFACE_H
#define PREPARE_INDIR_ARGS_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(PrepareIndirectArgs)

const int INOUT_COUNTERS_BUF_SLOT = 0;
const int OUT_INDIR_ARGS_SLOT = 1;

INTERFACE_END

#endif // PREPARE_INDIR_ARGS_INTERFACE_H