#ifndef SORT_SET_HEAD_FLAGS_INTERFACE_H
#define SORT_SET_HEAD_FLAGS_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(SortSetHeadFlags)

const int LOCAL_GROUP_SIZE_X = 64;

const int INPUT_BUF_SLOT = 1;
const int COUNTERS_BUF_SLOT = 2;

const int OUT_HEAD_FLAGS_BUF_SLOT = 0;

INTERFACE_END

#endif // SORT_SET_HEAD_FLAGS_INTERFACE_H