name: 'Test'
inputs:
  bin-dir:
    required: true
  out-dir:
    required: true
  test-args:
    required: true
  sde-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        WORK_DIR=`pwd`
        mkdir $WORK_DIR/${{ inputs.out-dir }}
        cd ../../builds/Ray/tests
        sde ${{ inputs.sde-args }} -- $WORK_DIR/${{ inputs.bin-dir }}/test_Ray ${{ inputs.test-args }} | tee $WORK_DIR/${{ inputs.out-dir }}/test_Ray_output.txt
      shell: bash
    - run: |
        WORK_DIR=`pwd`
        cd ../../builds/Ray/tests
        cp test_data/errors.txt $WORK_DIR/${{ inputs.out-dir }} || true
      if: always()
      shell: bash
