DECORATE(Nearest,   VK_FILTER_NEAREST,  VK_SAMPLER_MIPMAP_MODE_NEAREST, D3D12_FILTER_MIN_MAG_MIP_POINT)
DECORATE(Bilinear,  VK_FILTER_LINEAR,   VK_SAMPLER_MIPMAP_MODE_NEAREST, D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT)
DECORATE(Trilinear, VK_FILTER_LINEAR,   VK_SAMPLER_MIPMAP_MODE_LINEAR,  D3D12_FILTER_MIN_MAG_MIP_LINEAR)